[profile.default]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [{ access = "read", path = "./"}]
evm_version = "shanghai"

[rpc_endpoints]
worldchain_sepolia = "https://worldchain-mainnet.g.alchemy.com/public"
